# This workflow will install Python dependencies, run tests and lint with a variety of Python versions

name: Python package

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "main" ]

jobs:
    run-tests:
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest]
                python-version:
                    - "3.8"
                    - "3.9"
                    - "3.10"
        name: Test
        runs-on: ${{ matrix.os }}

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Python
              uses: actions/setup-python@v4
              with:
                python-version: ${{ matrix.python-version }}

            - name: Install dependencies
              run: python -m pip install pytest

            - name: Run Tests
              run: pytest _test_mysql_connection.py